### ISSUE TITLE
Error with wandb

### ISSUE THREAD

**Issue by Maxtoq** [marlbenchmark/off-policy#5]
Hello, I have encountered some problems. I wonder if you can help me.
that:Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: zhouweiqing (use wandb login --relogin to force relogin)
wandb: ERROR Error while calling W&B API: project not found (<Response [404]>)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql
i can not solve it

_Originally posted by @zhouweiqing-star in https://github.com/marlbenchmark/off-policy/issues/3#issuecomment-1049665762_

**Comment by Maxtoq** [comment]
@zhouweiqing-star
To answer your question here, I did have some similar problem with WanDB.
Do you want to use wandb or not ?
If not, you can use the `--use_wandb` argument in the command line to **not** use wandb, but Tensorboard instead, as it is explained here https://github.com/marlbenchmark/off-policy#3train.

**Comment by zhouweiqing-star** [comment]
Thank you very much for your answer. I'll try it myself.

**Comment by zhouweiqing-star** [comment]
> @zhouweiqing-star To answer your question here, I did have some similar problem with WanDB. Do you want to use wandb or not ? If not, you can use the `--use_wandb` argument in the command line to **not** use wandb, but Tensorboard instead, as it is explained here https://github.com/marlbenchmark/off-policy#3train.

Thank you very much for your answer. I'll try it myself.
