### ISSUE TITLE
MADDPG rewards are getting higher and higher

### ISSUE THREAD

**Issue by ollehhello** [marlbenchmark/off-policy#7]
Hello, I train MADDPG to get higher and higher rew
![image](https://user-images.githubusercontent.com/48572954/160052252-9e0d2777-610f-41bf-8310-7e1e801281bf.png)
ards in the context of simple_spread?

**Comment by mawuji88** [comment]
I encountered the same situation. Have you solved it？

**Comment by AnnXie2001** [comment]
Have you solved it？ I encounter the same problem
